name: slack notification for pull-request
on:
  pull_request:
    types: [opened, reopened]
jobs:
  slack_notification:
    name: pull-request notification
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Send notification to Slack
        uses: 8398a7/action-slack@v3.2.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          fields: repo,message,workflow,job,ref,commit
          author_name: Github Action Slack
          text: |
            풀 리퀘스트가 ${{ github.event.pull_request.state }}되었습니다.
            제목: ${{ github.event.pull_request.title }}
            작성자: @${{ github.event.pull_request.user.login }}
            링크: ${{ github.event.pull_request.html_url }}
